export default {
    INIT_MUSIC_INFO:'INIT_MUSIC_INFO',
    SWITCH_STATUS:'SWITCH_STATUS',
    // MUSIC_PAUSE:'MUSIC_PAUSE',
    // MUSIC_PLAY:'MUSIC_PLAY',
    MUSIC_NEXT:'MUSIC_NEXT',
    MUSIC_PREV:'MUSIC_PREV',
    MUSIC_CURRENT:'MUSIC_CURRENT',
    MUSIC_CURRENT_TIME_SET:'MUSIC_CURRENT_TIME_SET',
    MUSIC_DRAGE_TIME_SET:'MUSIC_DRAGE_TIME_SET',
    VOLUME_SET:'VOLUME_SET',
    WINDOW_RESIZE:'WINDOW_RESIZE',
    MUSIC_PLAY_BY_INDEX:'MUSIC_PLAY_BY_INDEX',
    UNDO_CONTROL:'UNDO_CONTROL'

}
